### ISSUE TITLE
attribute "boolean" is a string on frontend and needs eval to work

### ISSUE THREAD

**Issue by ivanjeremic** [senadir/interactive-block#2]
### Description

```
<ToggleControl
label="Muted"
help={attributes.muted ? "Enabled." : "Disabled."}
checked={attributes.muted}
onChange={(value) => setAttributes({ muted: value })}
/>
```

in block.json

```
"muted": {
"type": "boolean",
"default": false
}
```

In the frontend it only works when I use `eval()` because it is a string.

**Comment by senadir** [comment]
To properly use your attributes in the frontend, you need to parse them, as `dataset` won't parse them for you.

Use `withFilteredAttributes` from `@woocommerce/shared-hocs`.

So in `frontend.js`

```js
import { withFilteredAttributes } from "@woocommerce/shared-hocs";
import Block from "./block";
import metadata from "../block.json";

const FilteredBlock = withFilteredAttributes( metadata.attributes )( Block );

window.addEventListener( 'DOMContentLoaded', () => {
	const element = document.querySelector(
		'.wp-block-create-block-interactive-block'
	);
	if ( element ) {
		const attributes = { ...element.dataset };
		render(
			<Suspense fallback={ <div className="wp-block-placeholder" /> }>
				<FilteredBlock { ...attributes } />
			</Suspense>,
			element
		);
	}
} );
```

**Comment by ivanjeremic** [comment]
@senadir Interesting, I found all kind of interesting boilerplates and a while ago I built my own version which uses a `frontend.js` in this way 
```js
import ReactDOM from "react-dom";
import Wrapper from "./Wrapper";

window.addEventListener("DOMContentLoaded", () => {
	const blocks = document.querySelectorAll(".wp-block-create-my-block");

	if (blocks) {
		Array.from(blocks).forEach((block) => {
			const attributes = JSON.parse(block.dataset.attributes);
			ReactDOM.hydrate(<Wrapper {...attributes} />, block);
		});
	}
});
```

1.  What do you think about this approach compared to the one used in this repo?
2.  I see you don't loop over the elements so maybe this is overkill how I do it in my example? 
3. I also use `hydrade` and stringify/parse the attributes when I create/read  them, is this a good alternative to `@woocommerce/shared-hocs`?
4. I always ask myself are these hydrated interactive blocks shipping for each block the whole React.js lib over and over again? So for example if I add my `block-x` 5 times on a page does this mean I have 5 times the whole lib of `React.js` loaded on my frontend?

I would really appreciate your help in finding the best possible boilerplate and avoid any mistakes. Thanks
